# -*- coding: utf-8 -*-
"""SQD_H2O.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1euExnmnZtiyAvIyEf2E6_I--Y1319sMe
"""

from SQD_Alain import SQD

from qiskit_ibm_runtime import QiskitRuntimeService

QiskitRuntimeService.save_account(
    channel="ibm_cloud",
    token="  ",
    instance="  ",
    overwrite=True,
    set_as_default=True
)

SQD_H2O = SQD(
            #-------------
            # Run options
            #-------------
            backend_name = None,                                      # IBM cloud backend name. If None, then assign least busy device to backend
            do_plot_gate_map = True,                                  # Whether to plot the gate map
            load_bit_array_file = None,                               # If provided, function step_3 will load samples from this file
            save_bit_array_file = None,                               # If provided, function step_3 will save samples into this file
            n_ancillary_qubits = 0,                                   # Number of ancillary qubits
            run_on_QPU = False,                                       # Whether to run the quantum circuit on the target hardware
            nshots = 1000,                                            # Number of shots
            #---------------------------------------------------------
            # PySCF options
            # https://pyscf.org/user/gto.html#initializing-a-molecule
            #---------------------------------------------------------
            basis = "6-31g",                                          # Basis set
            atom = [["O", (0.0, 0.0, 0.0)], ["H", (0.0, 1.0, 0.0)], ["H", (0.0, 0.0, 1.0)]],
            #atom = [["C", (0.0, 0.0, 0.0)], ["O", (0.0, 0.0, 1.1283)]],
            symmetry = "C2v",                                          # Point group symmetry, https://pyscf.org/user/gto.html#point-group-symmetry
            n_frozen = 2,                                             # Number of frozen orbitals
            compute_exact_energy = True,                              # Whether to compute the exact energy with PySCF, cas.run().e_tot
            #----------------------------------------------------------------------------------
            # SQD options
            # https://github.com/Qiskit/qiskit-addon-sqd/blob/main/qiskit_addon_sqd/fermion.py
            #----------------------------------------------------------------------------------
            chem_accuracy = 1e-3,                                     # Chemical accuracy (+/- 1 milli-Hartree)
            energy_tol = 3e-5,                                        # Numerical tolerance for convergence of the energy
            occupancies_tol = 1e-3,                                   # Numerical tolerance for convergence of the average orbital occupancies
            max_iterations = 10,                                      # Limit on the number of configuration recovery iterations
            #-----------------------------------------------------------------------------------
            # Eigenstate solver options
            # https://github.com/Qiskit/qiskit-addon-sqd/blob/main/qiskit_addon_sqd/fermion.py
            #-----------------------------------------------------------------------------------
            num_batches = 3,                                          # The number of batches to subsample in each configuration recovery iteration
            samples_per_batch = 500,                                  # The number of bitstrings to include in each subsampled batch of bitstrings
            symmetrize_spin = True,                                   # Whether to always merge spin-alpha and spin-beta CI strings into a single list
            carryover_threshold = 1e-4,                               # Threshold for carrying over bitstrings with large CI weight from one iteration of configuration recovery to the next
            max_cycle = 200,                                          # The maximum number of Davidson cycles run by the eigenstate solver
            seed = 24,                                                # A seed for the pseudorandom number generator
            spin_sq = 0.0)                                            # spin square

circuit = SQD_H2O.step_1()

"""## Step 2: Optimize problem for quantum execution
Next, we optimize the circuit for a target hardware. We generate a staged pass manager using the [generate\_preset\_pass\_manager](https://docs.quantum.ibm.com/api/qiskit/transpiler_preset#generate_preset_pass_manager) function from qiskit with the specified `backend` and `initial_layout`.

We set the `pre_init` stage of the staged pass manager to `ffsim.qiskit.PRE_INIT`. It includes qiskit transpiler passes that decompose gates into orbital rotations and then merges the orbital rotations, resulting in fewer gates in the final circuit.
"""

isa_circuit = SQD_H2O.step_2()

"""## Step 3: Execute using Qiskit Primitives
As shown in the tutorial [Improving energy estimation of a chemistry Hamiltonian with SQD](https://github.com/Qiskit/qiskit-addon-sqd/blob/main/docs/tutorials/01_chemistry_hamiltonian.ipynb), we can use `Fake_Sherbrooke`, a fake 127-qubit backend from `qiskit_ibm_runtime` to emulate a real device, and generate random samples drawn from the uniform distribution. This approach is however not recommended, see [A case against uniform sampling](https://quantum.cloud.ibm.com/learning/en/courses/quantum-diagonalization-algorithms/sqd-overview#32-a-case-against-uniform-sampling).
"""

bit_array = SQD_H2O.step_3()

"""## Step 4: Post-process and return result to desired classical format
The first iteration of the self-consistent configuration recovery procedure uses the raw samples, after post-selection on symmetries, as input to the diagonalization process to obtain an estimate of the average orbital occupancies.

Subsequent iterations use these occupancies to generate new configurations from raw samples that violate the symmetries (i.e., are incorrect). These configurations are collected and then subsampled to produce batches, which are subsequently used to project the Hamiltonian and compute a ground-state estimate using an eigenstate solver.

We use the `diagonalize_fermionic_hamiltonian` function defined in [qiskit-addon-sqd/qiskit\_addon\_sqd/fermion.py](https://github.com/Qiskit/qiskit-addon-sqd/blob/main/qiskit_addon_sqd/fermion.py).

The solver included in the SQD addon uses PySCF's implementation of selected CI, specifically [pyscf.fci.selected_ci.kernel_fixed_space](https://pyscf.org/pyscf_api_docs/pyscf.fci.html#pyscf.fci.selected_ci.kernel_fixed_space)

The following parameters are user-tunable:
* `max_iterations`: Limit on the number of configuration recovery iterations.
* `num_batches`: The number of batches of configurations to subsample (i.e., the number of separate calls to the eigenstate solver).
* `samples_per_batch`: The number of unique configurations to include in each batch.
* `max_cycles`: The maximum number of Davidson cycles run by the eigenstate solver.
* `occupancies_tol`: Numerical tolerance for convergence of the average orbital occupancies. If the maximum change in absolute value of the average occupancy of an orbital between iterations is smaller than this value, then the configuration recovery loop will exit, if the energy has also converged (see the ``energy_tol`` argument).
* `energy_tol`: Numerical tolerance for convergence of the energy. If the change in energy between iterations is smaller than this value, then the configuration recovery loop will exit, if the occupancies have also converged (see the ``occupancies_tol`` argument).

"""

result, result_history = SQD_H2O.post_process()

plt = SQD_H2O.plot_energy_and_occupancy()

"""The first plot shows an estimation of the ground state energy within $\approx$ `1 milli-Hartree (mHa)`. The usual chemical accuracy is typically defined as `1 kcal/mol` $\approx$ `1.6 mHa`. However in the context of quantum chemistry, chemical accuracy is often approximated as `1 mHa`. The estimation of the energy can be improved by drawing more samples from the circuit, increasing the number of samples per batch and increasing the number of iterations.

The second plot shows the average occupancy of each spatial orbital after the final iteration. Both the spin-up and spin-down electrons occupy the first five orbitals with high probability.

# References

[1] Improving energy estimation of a chemistry Hamiltonian with SQD, https://github.com/Qiskit/qiskit-addon-sqd/blob/main/docs/tutorials/01_chemistry_hamiltonian.ipynb

[2] Sample-based Quantum Diagonalization (SQD), Quantum diagonalization algorithms, https://quantum.cloud.ibm.com/learning/en/courses/quantum-diagonalization-algorithms/sqd-overview

[3] Quantum diagonalization algorithms, IBM Quantum Platform, Quantum Learning, https://quantum.cloud.ibm.com/learning/en/courses/quantum-diagonalization-algorithms

[4] Antonio Mezzacapo: Quantum diagonalization methods for lattice models, IQuS - The InQubator For Quantum Simulation, Feb 19, 2025, https://www.youtube.com/watch?v=b1fhh71hY2g

[5] Javier Robledo-Moreno, Gavin Jones, Roberto Lo Nardo, Robert Davis, Lockheed Martin & IBM combine quantum computing with classical HPC in new research, IBM Quantum Research Blog, 22 May 2025, https://www.ibm.com/quantum/blog/lockheed-martin-sqd

[6] Ieva Liepuoniute, Kirstin D. Doney, Javier Robledo Moreno, Joshua A. Job, William S. Friend, Gavin O. Jones, Quantum-Centric Computational Study of Methylene Singlet and Triplet States, J. Chem. Theory Comput. 2025, 21, 10, 5062–5070, https://doi.org/10.1021/acs.jctc.5c00075

[7] Danil Kaliakin, Akhil Shajan, Fangchun Liang, Kenneth M. Merz Jr., Implicit Solvent Sample-Based Quantum Diagonalization,J. Phys. Chem. B 2025, 129, 23, 5788–5796, https://doi.org/10.1021/acs.jpcb.5c01030

[8] Deploy and Run the SQD IEF-PCM Function Template, qiskit-function-templates/chemistry/sqd_pcm/deploy_and_run.ipynb, https://github.com/qiskit-community/qiskit-function-templates/blob/main/chemistry/sqd_pcm/deploy_and_run.ipynb

[9] J. Robledo-Moreno et al., "Chemistry Beyond Exact Solutions on a Quantum-Centric Supercomputer" (2024), arXiv:quant-ph/2405.05068, https://arxiv.org/abs/2405.05068

[10] M. Motta et al., “Bridging physical intuition and hardware efficiency for correlated electronic states: the local unitary cluster Jastrow ansatz for electronic structure” (2023). Chem. Sci., 2023, 14, 11213, https://pubs.rsc.org/en/content/articlehtml/2023/sc/d3sc02516k

[11] Keita Kanno, Masaya Kohda, Ryosuke Imai, Sho Koh, Kosuke Mitarai, Wataru Mizukami, Yuya O. Nakagawa, Quantum-Selected Configuration Interaction: classical diagonalization of Hamiltonians in subspaces selected by quantum computers, arXiv:2302.11320 [quant-ph], https://doi.org/10.48550/arXiv.2302.11320

[12] Introduction to Qiskit patterns, https://quantum.cloud.ibm.com/docs/en/guides/intro-to-patterns

[13] Keeper L. Sharkey and Alain Chancé, Quantum Chemistry and Computing for the Curious: Illustrated with Python and Qiskit® code, Packt 2022, https://a.co/d/6YCwgPb

[14] Companion Jupyter notebook for Chapter 5 of the book Quantum Chemistry and Computing for the Curious: Illustrated with Python and Qiskit® code, https://github.com/AlainChance/Quantum-Chemistry-and-Computing-for-the-Curious/blob/main/Chapter_05_Variational_Quantum_Eigensolver_(VQE)_algorithm_V4.ipynb

[15] Taha Selim, Ad van der Avoird, Gerrit C. Groenenboom, State-to-state rovibrational transition rates for CO2 in the bend mode in collisions with He atoms, J. Chem. Phys. 159, 164310 (2023), https://doi.org/10.1063/5.0174787

## Qiskit packages versions
"""

import qiskit
import qiskit_ibm_runtime
import qiskit_aer

print(f'Qiskit: {qiskit.__version__}')
print(f'Qiskit IBM Runtime: {qiskit_ibm_runtime.__version__}')
print(f"Qiskit Aer version: {qiskit_aer.__version__}")

"""## Show Python version"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# which python
# python --version